{
	"version": 1638479790,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/navep-sheet0.png",
		"images/navep-sheet1.png",
		"images/inimigo1-sheet0.png",
		"images/inimigo1-sheet1.png",
		"images/inimigo1-sheet2.png",
		"images/tirop-sheet0.png",
		"images/gameback.png",
		"images/explosao-sheet0.png",
		"images/explosao-sheet1.png",
		"images/tirosec-sheet0.png",
		"images/inimigo2-sheet0.png",
		"images/inimigo2-sheet1.png",
		"images/inimigo2-sheet2.png",
		"images/inimigo3-sheet0.png",
		"images/inimigo3-sheet1.png",
		"images/inimigo3-sheet2.png",
		"images/botaocreditos-sheet0.png",
		"images/botaostart-sheet0.png",
		"images/inicioback.png",
		"images/inimigo4-sheet0.png",
		"images/nebuladefender.png",
		"images/gameover.png",
		"images/botaomenu-sheet0.png",
		"images/creditosback.png",
		"images/menuroxo-sheet0.png",
		"images/creditos-sheet0.png",
		"images/score2.png",
		"images/botaogameover-sheet0.png",
		"images/creditos2-sheet0.png",
		"images/botaoretry-sheet0.png",
		"media/synth pop.m4a",
		"media/synth pop.ogg",
		"media/botao.m4a",
		"media/botao.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/zaude.m4a",
		"media/zaude.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}